import uuid
from typing import Protocol

from dangerous_api.domain.user import FrontierAccount, User


class UserRepository(Protocol):
    async def add(self, user: User) -> None: ...
    async def get(self, user_id: uuid.UUID) -> User | None: ...
    async def get_by_login(self, login: str) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_frontier_id(self, frontier_id: int) -> User | None: ...
    async def link_frontier(
        self, user_id: uuid.UUID, account: FrontierAccount
    ) -> None: ...


class PasswordHasher(Protocol):
    dummy_hash: str

    def hash(self, password: str) -> str: ...
    def verify(self, password: str, hashed: str) -> bool: ...
