import uuid
from typing import Protocol

from inara.domain.user import FrontierAccount, User


class UserRepository(Protocol):
    async def add(self, user: User) -> None: ...
    async def get(self, user: User) -> None: ...
    async def get_by_login(self, user: User) -> User | None: ...
    async def get_by_frontier_id(self, frontier_id: int) -> User | None: ...
    async def link_frontier(
        self, user_id: uuid.UUID, account: FrontierAccount
    ) -> None: ...
